const Data = [
    {
        id: '0',
        name: 'True Alchemy',
        dev: 'Levrana',
        composition: 'Ecotine 0.5%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '5.90$',
        model: '/dropperbottle1.gltf',
        use: 'face',
        image: '/TrueAlchemy.jpg',
    },
    {
        id: '1',
        name: 'Facial Serum',
        dev: 'Levrana',
        composition: 'Hydrode 0.3%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '8.90$',
        model: '/dropperbottle2.gltf',
        use: 'face',
        image: '/FacialSerum.jpg',
    },
    {
        id: '2',
        name: 'Active Solution',
        dev: 'Levrana',
        composition: 'Saydone 0.2%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '480₽',
        model: '/dropperbottle3.gltf',
        use: 'body',
        image: '/ActiveSolution.jpg',
    },
    {
        id: '3',
        name: 'Active Serum',
        dev: 'Levrana',
        composition: 'Arginine 2.7%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '3.50$',
        model: '/dropperbottle4.gltf',
        use: 'body',
        image: '/ActiveSerum.jpg',
    },
    {
        id: '4',
        name: 'Bi-Phase Hydration',
        dev: 'Levrana',
        composition: 'Glyceryl 1,2%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '9.90$',
        model: '/dropperbottle5.gltf',
        use: 'men',
        image: '/BiPhaseHydration.jpg',
    },
    {
        id: '5',
        name: 'Natural Cosmo',
        dev: 'Levrana',
        composition: 'AHA Acids 5,1%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '9.90$',
        model: '/dropperbottle6.gltf',
        use: 'men',
        image: '/NaturalCosmo.jpg',
    },
    {
        id: '6',
        name: 'Condense Agent',
        dev: 'Levrana',
        composition: 'Inulin 5%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '5.90$',
        model: '/dropperbottle7.gltf',
        use: 'men',
        image: '/CondenseAgent.jpg',
    },
    {
        id: '7',
        name: 'X-Fresh',
        dev: 'Levrana',
        composition: 'Hyaluronic acid 3,0%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '12.90$',
        model: '/dropperbottle8.gltf',
        use: 'body',
        image: '/XFresh.jpg',
    },
    {
        id: '8',
        name: 'Aloe Hydrator',
        dev: 'Levrana',
        composition: 'Salicylic Acid 2%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '8.90$',
        model: '/dropperbottle9.gltf',
        use: 'face',
        image: '/AloeHydrator.jpg',
    },
    {
        id: '9',
        name: 'Fluid Clenser',
        dev: 'Levrana',
        composition: 'Vitamin C 3%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '3.90$',
        model: '/dropperbottle10.gltf',
        use: 'sale',
        image: '/FluidClenser.jpg',
    },
    {
        id: '10',
        name: 'Serum Gel',
        dev: 'Levrana',
        composition: 'Calamine & Arginine',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '9.90$',
        model: '/dropperbottle11.gltf',
        use: 'sale',
        image: '/SerumGel.jpg',
    },
    {
        id: '11',
        name: 'Active Rest',
        dev: 'Levrana',
        composition: 'Sodium Hyaluronate 2.1%',
        description: ' Curabitur id dui augue. Duis gravida mi in magna fermentum, in congue tellus posuere. Nulla facilisi. Curabitur lorem elit, pulvinar eget nisi vel, pretium cursus sem.',
        purpose1: "-Aliquam erat volutpat. Cras vulputate pharetra.",
        purpose2: "-Tellus id tincidunt. Aliquam hendrerit nunc eu tortor pulvinar commodo.",
        effect: 'tiam condimentum porta odio quis porttitor. Donec quis ullamcorper ex, non commodo urna. Aenean non maximus velit.',
        price: '7.90$',
        model: '/dropperbottle12.gltf',
        use: 'sale',
        image: '/ActiveRest.jpg',
    },
    
]

export default Data